version: '3.7'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=1.1.0
        - NODE_VERSION=current
    image: ${PROJECT_NAME}/nodejs
    working_dir: /var/www/html
    restart: unless-stopped
    privileged: true
    tty: true
    stdin_open: true
    mem_limit: 3g
    # entrypoint: ./entrypoint.sh
    env_file: ./.env
    ports:
      - ${DOCKER_APP_PORT}:${PORT}
    volumes:
      - ./code/:/var/www/html
